all:
  vars:
    ansible_user: ansible

  children:
    edge:
      hosts:
        edge01.lab.local:
          ansible_host: 10.10.10.10

    ci:
      hosts:
        ci01.lab.local:
          ansible_host: 10.10.10.11

    app:
      hosts:
        app01.lab.local:
          ansible_host: 10.10.10.20
        app02.lab.local:
          ansible_host: 10.10.10.21

    ops:
      hosts:
        ops01.lab.local:
          ansible_host: 10.10.10.30
