- name: Deploy Flask app
  hosts:  app
  gather_facts: true
  become: true

  vars:
    app_repo_path: "/home/ansible/enterprise-app-lab"
    app_repo_url: "git@github.com:martirentani8902/enterprise-app-lab.git"
    app_repo_branch: "main"
    app_dir:  "/opt/flaskapp"
    app_user: "flaskapp"
    app_group:  "flaskapp"
    venv_path:  "/opt/flaskapp-venv/.venv"
    service_name: "flaskapp"


  tasks:

    - name: Actualizar repo de la app
      git:
        repo: "{{ app_repo_url  }}"
        dest: "{{ app_repo_path }}"
        version: "{{  app_repo_branch }}"
        update: yes
      delegate_to: localhost
      run_once: true
      become: false

    - name: Obtener commit actual de la app
      command: git rev-parse --short HEAD
      args:
        chdir: "{{ app_repo_path }}"
      delegate_to: localhost
      run_once: true
      become: false
      register: git_commit

    - name: Definir release_id desde commit
      set_fact:
        release_id: "{{ git_commit.stdout }}"
      run_once: true

    - name: Crear artefacto
      archive:
        path: "{{ app_repo_path }}/*"
        dest: "/tmp/flaskapp.tar.gz" 
        exclude_path: 
          - "{{ app_repo_path }}/README.md" 
          - "{{ app_repo_path }}/.git"
          - "{{ app_repo_path }}/.env.example"
      delegate_to: localhost
      run_once: true
      become: false

    - name: Copiar artefacto a servidores app
      copy:
        src: "/tmp/flaskapp.tar.gz"
        dest: "/tmp/flaskapp.tar.gz"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0640"

    - name: Asegurar directorio de release
      file:
        path: "{{ app_dir }}/releases/{{  release_id  }}"
        state:  directory
        owner:  "{{ app_user  }}"
        group:  "{{ app_group }}"
        mode: "0770"

    - name: Extraer release
      unarchive:
        src: "/tmp/flaskapp.tar.gz"
        dest: "{{ app_dir }}/releases/{{ release_id }}"
        remote_src: true

    - name: Instalar dependencias Python
      pip:
        requirements: "{{ app_dir }}/releases/{{  release_id  }}/requirements.txt"
        virtualenv: "{{ venv_path }}"
        virtualenv_python:  python3

    - name: Apuntar current a la nueva release
      file:
        src: "{{ app_dir }}/releases/{{ release_id }}"
        dest: "{{ app_dir }}/current"
        state: link
        owner: "{{ app_user }}"
        group: "{{ app_group }}"

    - name: Reiniciar servicio Flask  app
      systemd:
        name: "{{ service_name  }}"
        state:  restarted
        enabled:  true
        daemon_reload:  true

    - name: Verificar health de la app
      uri:
        url: "http://127.0.0.1:5000/health"
        method: GET
        return_content: true
        status_code: 200
      register: flask_health
      retries: 10
      delay: 2
      until:
        - flask_health.status == 200
        - flask_health.content is search("ok")

    - name: Mostrar respuesta de health
      debug:
          var:  flask_health.content

