---
- name: Instalar Zabbix Agent 2
  hosts: all
  become: true
  vars:
    zabbix_version: "7.0"
    zabbix_release_deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/pool/main/z/zabbix-release/zabbix-release_latest_{{  zabbix_version  }}+debian13_all.deb"
    zabbix_release_local: "/tmp/zabbix-release_latest+debian13_all.deb"

  tasks:

    - name: Habilitar conexion a apt-cache-ng
      copy:
        dest: "/etc/apt/apt.conf.d/01proxy"
        content: |
          Acquire::http::Proxy "http://10.10.10.10:3142";

    - name: Descargar paquete release de Zabbix
      get_url:
        url: "{{ zabbix_release_deb }}"
        dest: "{{ zabbix_release_local }}"
        mode: "0644"

    - name: Instalar repositorio oficial de Zabbix
      apt:
        deb: "{{ zabbix_release_local }}"

    - name: Actualizar cache de apt
      apt:
        update_cache: true

    - name: Instalar zabbix-agent2
      apt:
        name: zabbix-agent2
        state: present

    - name: Habilitar y arrancar zabbix-agent2
      systemd:
        name: zabbix-agent2
        enabled: true
        state: started
